2022-09-06 00:37:31,743 : INFO : logger : Outlier for Sales is fixed
2022-09-06 00:37:31,743 : INFO : logger : Outlier for Sales is fixed
2022-09-06 00:37:31,743 : INFO : logger : Outlier for Sales is fixed
2022-09-06 00:43:04,671 : INFO : logger : Outlier for CompetitionDistance is fixed
2022-09-06 00:43:04,671 : INFO : logger : Outlier for CompetitionDistance is fixed
2022-09-06 00:43:04,671 : INFO : logger : Outlier for CompetitionDistance is fixed
2022-09-07 17:06:28,475 : INFO : logger : Outlier for Sales is fixed
2022-09-07 17:06:28,475 : INFO : logger : Outlier for Sales is fixed
2022-09-07 17:06:28,475 : INFO : logger : Outlier for Sales is fixed
2022-09-07 17:06:29,562 : INFO : logger : Outlier for CompetitionDistance is fixed
2022-09-07 17:06:29,562 : INFO : logger : Outlier for CompetitionDistance is fixed
2022-09-07 17:06:29,562 : INFO : logger : Outlier for CompetitionDistance is fixed
2022-09-08 11:16:53,681 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:16:53,681 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:16:53,802 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:16:53,802 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:28:19,926 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:28:19,926 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:28:20,047 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:28:20,047 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:28:26,620 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:28:26,620 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:28:26,620 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:28:26,621 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:28:26,621 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:28:26,621 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:28:26,622 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:28:26,622 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:28:26,622 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:28:26,623 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:28:26,623 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:28:26,623 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:35:50,947 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:35:50,947 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:35:50,947 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:35:50,947 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:35:51,072 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:35:51,072 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:35:51,072 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:35:51,072 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:35:52,745 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:35:52,745 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:35:52,745 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:35:52,745 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:35:52,745 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:35:52,747 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,747 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,747 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,747 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,747 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,752 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,752 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,752 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,752 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,752 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:35:52,754 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:35:52,754 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:35:52,754 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:35:52,754 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:35:52,754 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:44:10,539 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:44:10,539 : INFO : logger : Outlier for Customers is fixed
2022-09-08 11:44:10,709 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:44:10,709 : INFO : logger : Outlier for Sales is fixed
2022-09-08 11:44:14,348 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:44:14,348 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:44:14,348 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 11:44:14,348 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:44:14,348 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:44:14,348 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:44:14,349 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:44:14,349 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:44:14,349 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 11:44:14,350 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:44:14,350 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:44:14,350 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 11:44:32,375 : INFO : logger : Successfully Added Season Column
2022-09-08 11:44:32,375 : INFO : logger : Successfully Added Season Column
2022-09-08 11:44:32,375 : INFO : logger : Successfully Added Season Column
2022-09-08 13:05:19,587 : INFO : logger : Outlier for Customers is fixed
2022-09-08 13:05:19,587 : INFO : logger : Outlier for Customers is fixed
2022-09-08 13:05:19,587 : INFO : logger : Outlier for Customers is fixed
2022-09-08 13:05:19,587 : INFO : logger : Outlier for Customers is fixed
2022-09-08 13:05:19,700 : INFO : logger : Outlier for Sales is fixed
2022-09-08 13:05:19,700 : INFO : logger : Outlier for Sales is fixed
2022-09-08 13:05:19,700 : INFO : logger : Outlier for Sales is fixed
2022-09-08 13:05:19,700 : INFO : logger : Outlier for Sales is fixed
2022-09-08 13:05:23,814 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 13:05:23,814 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 13:05:23,814 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 13:05:23,814 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 13:05:23,814 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-08 13:05:23,815 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,815 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,815 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,815 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,815 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,816 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,816 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,816 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,816 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,816 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-08 13:05:23,817 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 13:05:23,817 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 13:05:23,817 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 13:05:23,817 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 13:05:23,817 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-08 13:05:27,498 : INFO : logger : Successfully Added Season Column
2022-09-08 13:05:27,498 : INFO : logger : Successfully Added Season Column
2022-09-08 13:05:27,498 : INFO : logger : Successfully Added Season Column
2022-09-08 13:05:27,498 : INFO : logger : Successfully Added Season Column
2022-09-08 13:05:27,498 : INFO : logger : Successfully Added Season Column
2022-09-09 00:12:09,000 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:12:09,000 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:12:09,000 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:12:09,000 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:12:09,000 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:12:09,000 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:12:09,127 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:12:09,127 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:12:09,127 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:12:09,127 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:12:09,127 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:12:09,127 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:13:27,470 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:13:27,470 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:13:27,587 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:13:27,587 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:14:16,933 : INFO : logger : Successfully Added Season Column
2022-09-09 00:14:16,933 : INFO : logger : Successfully Added Season Column
2022-09-09 00:14:16,933 : INFO : logger : Successfully Added Season Column
2022-09-09 00:47:17,582 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:47:17,582 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:47:17,690 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:47:17,690 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:47:21,474 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:47:21,474 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:47:21,474 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:47:21,475 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:47:21,475 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:47:21,475 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:47:21,477 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:47:21,477 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:47:21,477 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:47:21,479 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:47:21,479 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:47:21,479 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:47:27,319 : INFO : logger : Successfully Added Season Column
2022-09-09 00:47:27,319 : INFO : logger : Successfully Added Season Column
2022-09-09 00:47:27,319 : INFO : logger : Successfully Added Season Column
2022-09-09 00:52:16,483 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:52:16,483 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:52:16,595 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:52:16,595 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:52:17,841 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:52:17,841 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:52:17,841 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:52:17,842 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:52:17,842 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:52:17,842 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:52:17,842 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:52:17,842 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:52:17,842 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:52:17,843 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:52:17,843 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:52:17,843 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:52:18,504 : INFO : logger : Successfully Added Season Column
2022-09-09 00:52:18,504 : INFO : logger : Successfully Added Season Column
2022-09-09 00:52:18,504 : INFO : logger : Successfully Added Season Column
2022-09-09 00:56:25,093 : ERROR : logger : Failed to Add WeekDay Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 98, in add_week_day
    self.df.insert(date_index + 1, 'WeekDay',
  File "c:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4440, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert WeekDay, already exists
2022-09-09 00:56:25,093 : ERROR : logger : Failed to Add WeekDay Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 98, in add_week_day
    self.df.insert(date_index + 1, 'WeekDay',
  File "c:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4440, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert WeekDay, already exists
2022-09-09 00:56:25,093 : ERROR : logger : Failed to Add WeekDay Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 98, in add_week_day
    self.df.insert(date_index + 1, 'WeekDay',
  File "c:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4440, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert WeekDay, already exists
2022-09-09 00:56:39,062 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:56:39,062 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:56:39,062 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:57:03,398 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:57:03,398 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:57:03,398 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:57:05,998 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:57:05,998 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:57:05,998 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:58:30,614 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:58:30,614 : INFO : logger : Outlier for Customers is fixed
2022-09-09 00:58:30,733 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:58:30,733 : INFO : logger : Outlier for Sales is fixed
2022-09-09 00:58:35,383 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:58:35,383 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:58:35,383 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 00:58:36,397 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:58:36,397 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:58:36,397 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:58:37,736 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:58:37,736 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:58:37,736 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 00:58:39,001 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:58:39,001 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:58:39,001 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 00:58:52,372 : INFO : logger : Successfully Added Season Column
2022-09-09 00:58:52,372 : INFO : logger : Successfully Added Season Column
2022-09-09 00:58:52,372 : INFO : logger : Successfully Added Season Column
2022-09-09 01:02:54,745 : INFO : logger : Outlier for Customers is fixed
2022-09-09 01:02:54,745 : INFO : logger : Outlier for Customers is fixed
2022-09-09 01:02:54,867 : INFO : logger : Outlier for Sales is fixed
2022-09-09 01:02:54,867 : INFO : logger : Outlier for Sales is fixed
2022-09-09 01:03:00,322 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 01:03:00,322 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 01:03:00,322 : INFO : logger : Successfully Added WeekDay Column to the DataFrame
2022-09-09 01:03:01,202 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 01:03:01,202 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 01:03:01,202 : ERROR : logger : Failed to Add DaysToHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 111, in add_number_of_days_to_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 01:03:02,015 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 01:03:02,015 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 01:03:02,015 : ERROR : logger : Failed to Add DaysAfterHoliday Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 147, in add_number_of_days_after_holiday
    modified_index = self.modify_holiday_list(
AttributeError: 'dataProcessor' object has no attribute 'modify_holiday_list'
2022-09-09 01:03:03,295 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 01:03:03,295 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 01:03:03,295 : ERROR : logger : Failed to Add MonthTiming Column
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\clone\pharmaceutical_sales_prediction\notebooks\../scripts\data_preProcessing.py", line 183, in add_month_timing
    self.df[day_col].apply(self.return_day_status_in_month))
AttributeError: 'dataProcessor' object has no attribute 'return_day_status_in_month'
2022-09-09 01:03:07,703 : INFO : logger : Successfully Added Season Column
2022-09-09 01:03:07,703 : INFO : logger : Successfully Added Season Column
2022-09-09 01:03:07,703 : INFO : logger : Successfully Added Season Column
